MODEL:
  NAME: "deeplab_resnet101"
  WEIGHTS: "https://download.pytorch.org/models/resnet101-5d3b4d8f.pth"
  FREEZE_BN: False
DATASETS:
  SOURCE_TRAIN: "cityscapes_self_distill_train"
  TARGET_TRAIN: "cityscapes_train"
  TEST: "cityscapes_val"
INPUT:
  SOURCE_INPUT_SIZE_TRAIN: (1024, 512)
  INPUT_SIZE_TEST: (2048, 1024)
  INPUT_SCALES_TRAIN: (0.5, 1.5)
  HORIZONTAL_FLIP_PROB_TRAIN: 0.5
  BRIGHTNESS: 0.5
  CONTRAST: 0.5
  SATURATION: 0.5
  HUE: 0.2
SOLVER:
  BASE_LR: 2.5e-4
  BASE_LR_D: 0.0001
  MAX_ITER: 62500
  STOP_ITER: 40000
  BATCH_SIZE: 8
ENT_NORM: True
ENT_NORM_FACTOR: 0.5
ENT_THRESH: 0.01
